"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import MobileNav from '@/components/MobileNav'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import { NextUIProvider } from '@nextui-org/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <NextUIProvider>
            <MobileNav/>
            <Nav/>
              {children}
            <Footer/>
          </NextUIProvider>
        </body>
      </html>
  )
}
