"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import MobileNav from '@/components/MobileNav'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={inter.className}>
        <MobileNav/>
        <Nav/>
          {children}
        <Footer/>
        </body>
      </html>
  )
}
